apiVersion: v1
kind: Service
metadata:
   name: nginx-hello-world
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
     - port: 80
       targetPort: 80
       nodePort: 32042

